CREATE TABLE technology (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) NOT NULL UNIQUE,
    icon VARCHAR(100),
    website VARCHAR(2048),
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_technology_display_order ON technology (display_order);

CREATE TABLE project_technology (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project (id),
    technology_id BIGINT NOT NULL REFERENCES technology (id),
    display_order INTEGER NOT NULL,
    CONSTRAINT uq_project_technology UNIQUE (project_id, technology_id)
);

CREATE INDEX idx_project_technology_project_id ON project_technology (project_id);
CREATE INDEX idx_project_technology_technology_id ON project_technology (technology_id);
