INSERT INTO project (
    id,
    slug,
    title,
    headline,
    description,
    challenge,
    solution,
    image_url,
    github_url,
    demo_url,
    featured,
    display_order,
    created_at,
    updated_at
) VALUES
(
    1,
    'portfolio',
    'Bartholdy Portfolio',
    'A modern portfolio built with Angular 22.',
    'Personal portfolio inspired by modern developer websites, built as part of a Java + Angular immersion challenge.',
    'Create a professional portfolio while applying modern Angular concepts from scratch, going beyond the base course project.',
    'Built with Standalone Components, the new Control Flow syntax, a reusable design system and a component-based architecture, with all content driven by typed data files for easy maintenance.',
    '/assets/images/bartholdyportfolio.png',
    'https://github.com/dhbart/bartholdy-portfolio',
    '#',
    FALSE,
    1,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    2,
    'budgeting',
    'Budgeting — Voice-Driven Finance API',
    'A personal finance API you talk to.',
    'A voice-driven personal finance API built with Spring Boot and Spring AI. It transcribes spoken audio, uses AI tool calling to execute real use cases like creating and listing transactions, and replies back with synthesized speech.',
    'Most finance-tracking apps still require manual form-filling. The goal was to let a user simply speak a transaction out loud — "I spent 40 on groceries" — and have the system understand, execute and confirm it, entirely by voice.',
    'The API transcribes incoming audio, passes the resulting text to an LLM configured with Spring AI Tool Calling, which decides which backend function to invoke (create transaction, list transactions, etc.). The result is converted back into synthesized speech, closing the loop from voice in to voice out without any manual UI interaction.',
    '/assets/images/budgeting.png',
    'https://github.com/dhbart/budgeting',
    '#',
    TRUE,
    2,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    3,
    'crescer-juntos',
    'Crescer Juntos',
    'A family routines and rewards API, built with DDD.',
    'A REST API for managing family routines, children''s tasks, points and rewards — built with Java 21, Spring Boot, PostgreSQL and OpenAPI, following Domain-Driven Design and Clean Architecture.',
    'Model a real-world domain — family routines, task assignment, point accumulation and reward redemption — in a way that keeps business rules isolated from framework and persistence details, rather than letting logic leak into controllers and entities.',
    'Applied Domain-Driven Design and Clean Architecture to separate the domain model from infrastructure concerns, documenting the API with OpenAPI and using Gradle and PostgreSQL as the build and persistence layer. This project doubles as hands-on practice with concepts I was studying at the theory level (DDD, TDD) and had not yet applied in a production codebase.',
    '/assets/images/crescer-juntos.png',
    'https://github.com/dhbart/crescer-juntos',
    '#',
    FALSE,
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    4,
    'tickets-marketplace',
    'Tickets Marketplace',
    'Exploring multi-database persistence and distributed seat locking.',
    'A Spring Boot application exploring multi-database persistence (MySQL, PostgreSQL and MongoDB) with Redis caching and distributed seat locking, built during a Java backend bootcamp.',
    'In a ticket marketplace, two users can try to buy the same seat at the same time. The challenge was preventing that race condition — and double-booking — across a system using more than one type of database for different parts of the domain.',
    'Implemented distributed seat locking so a seat is reserved for a single purchase flow at a time, with Redis handling caching for frequently read data. The persistence layer intentionally mixes MySQL, PostgreSQL and MongoDB to practice choosing the right database per data shape rather than defaulting to a single one.',
    '/assets/images/ticketing.png',
    'https://github.com/dhbart/TicketsMarketplace',
    '#',
    FALSE,
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    5,
    'movie-api',
    'Movie Explorer API',
    'A movie API built around three classic design patterns.',
    'A REST API built with Java 21 and Spring Boot, integrating with the TMDB API to browse and manage movies, applying the Singleton, Strategy and Facade design patterns.',
    'Consume an external API (TMDB) while keeping the integration swappable and the internal service logic decoupled from any single external provider or search strategy.',
    'Used the Facade pattern to expose a simplified interface over the TMDB integration, Strategy to allow different movie-search behaviors to be swapped without changing calling code, and Singleton for shared stateless services — documenting all endpoints with Swagger/OpenAPI.',
    '/assets/images/movie-api.png',
    'https://github.com/dhbart/desafio-design-patterns',
    '#',
    FALSE,
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
